org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false
kotlin.jvm.target.validation.mode=warning

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.157.0+26.2

mod_version=0.0.9
maven_group=com.aerosync
archives_base_name=aerosync-fabric-mc26.2

iroh_version=1.1.0
kotlin_version=2.2.21
kotlin_coroutines_version=1.9.0
jna_version=5.15.0
